name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_and_build:
    runs-on: ubuntu-latest
    container: docker:latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Check for existing lsb-release package
        id: check_lsb_release
        run: |
          if ! command -v lsb_release &> /dev/null
          then
            echo "lsb-release not found, installing..."
            sudo apt-get update
            sudo apt-get install -y lsb-release
          else
            echo "lsb-release already installed."
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USER_NAME}}
            password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Build and push Python Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./python-server
          push: true
          tags: charlesozo/omnicron-pys:latest
          build-args: |
            MY_API_KEY=${{ secrets.MY_API_KEY }}
            GROK_API_KEY=${{ secrets.GROK_API_KEY }}
            GEMINI_PRO_API_KEY=${{ secrets.GEMINI_PRO_API_KEY }}