name: Python CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME}}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN}}

      - name: Run Pylint and check pylint
        env:
          PYTHON_VERSION: "3.11"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y python${PYTHON_VERSION}
          python${PYTHON_VERSION} -m pip install pylint
          python${PYTHON_VERSION} -m pip install --upgrade -r python-server/requirements.txt
          pylint python-server
          pylint --fail-under=8.0 **/*.py

      - name: Build and push Python Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./python-server
          push: true
          tags: charlesozo/omnicron-pys:latest, charlesozo/${{github.run_number}}
          build-args: |
            MY_API_KEY=${{ secrets.MY_API_KEY }}
            GROK_API_KEY=${{ secrets.GROK_API_KEY }}
            GEMINI_PRO_API_KEY=${{ secrets.GEMINI_PRO_API_KEY }}
